/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendaftaran;

/**
 *
 * @author Swift 3
 */
public class Form_Konsultan extends javax.swing.JFrame {

    /**
     * Creates new form Form_Pelatihan
     */
    public Form_Konsultan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        jenis = new javax.swing.JLabel();
        tambahan = new javax.swing.JLabel();
        tambahan2 = new javax.swing.JLabel();
        tempat = new javax.swing.JLabel();
        metode = new javax.swing.JLabel();
        combojenis = new javax.swing.JComboBox<>();
        ttambahan = new javax.swing.JTextField();
        combometode = new javax.swing.JComboBox<>();
        nomor = new javax.swing.JLabel();
        combometode1 = new javax.swing.JComboBox<>();
        metode1 = new javax.swing.JLabel();
        ttempat1 = new javax.swing.JTextField();
        combometode2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul.setFont(new java.awt.Font("Cambria", 1, 26)); // NOI18N
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("FORM KONSULTAN");
        jPanel1.add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 250, 49));

        jenis.setText("Jenis Jasa Konsultan / Kegiatan kami");
        jPanel1.add(jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 230, -1));

        tambahan.setText("Tambahkan Nama Jasa Konsultansi");
        tambahan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(tambahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 220, 31));

        tambahan2.setText("yang diajukan Bapak / Ibu");
        tambahan2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(tambahan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 28));

        tempat.setText("Tempat Konsultansi / Kegiatan");
        jPanel1.add(tempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 304, -1, 20));

        metode.setText("Nama Peneliti");
        jPanel1.add(metode, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 180, 20));

        combojenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Silahkan pilih--", "Pendampingan Studi Kelayakan Rumah Sakit", "Pendampingan Masterplan Rumah Sakit", "Pendampingan BLU & BLUD Rumah Sakit", "Pendampingan Pembuatan Renstra Bisnis Rumah Sakit", "Analisis Kebijakan Kesehatan", "Pendampingan Penyusunan Sistem Kesehatan Daerah", "Lainnya .." }));
        jPanel1.add(combojenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 390, -1));
        jPanel1.add(ttambahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 390, 70));

        combometode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Silahkan Pilih--" }));
        jPanel1.add(combometode, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 390, -1));

        nomor.setText("Nomor Kegiatan");
        jPanel1.add(nomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 20));

        combometode1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Online", "Offline", "Hybrid", "Onsite" }));
        jPanel1.add(combometode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 240, -1));

        metode1.setText("Metode Konsultansi yang diajukan");
        jPanel1.add(metode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 180, 20));
        jPanel1.add(ttempat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 390, -1));

        combometode2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Silahkan Pilih--" }));
        jPanel1.add(combometode2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 390, -1));

        jButton2.setText("Cancel");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, -1, -1));

        jButton4.setText("Save");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jButton5.setText("Edit");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        jButton6.setText("Delete");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 507, 770, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Konsultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Konsultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Konsultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Konsultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Konsultan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combojenis;
    private javax.swing.JComboBox<String> combometode;
    private javax.swing.JComboBox<String> combometode1;
    private javax.swing.JComboBox<String> combometode2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jenis;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel metode;
    private javax.swing.JLabel metode1;
    private javax.swing.JLabel nomor;
    private javax.swing.JLabel tambahan;
    private javax.swing.JLabel tambahan2;
    private javax.swing.JLabel tempat;
    private javax.swing.JTextField ttambahan;
    private javax.swing.JTextField ttempat1;
    // End of variables declaration//GEN-END:variables
}
