/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendaftaran;
import java.util.Scanner;
import javax.swing.JOptionPane;
 

/**
 *
 * @author Swift 3
 */
public class FormKegiatan extends javax.swing.JFrame {
String idkegiatan,s;
int a;
    /**
     * Creates new form FormKegiatan
     */
    public FormKegiatan() {
        initComponents();
    }
public void getform(){
    idkegiatan=(String) this.tipekegiatan.getSelectedItem();
    if (idkegiatan.equals("Konsultasi"))
    {
        new Form_Konsultan().setVisible(true);
        this.dispose();
    }
    else if (idkegiatan.equals("Pelatihan"))
    {
        new Form_Pelatihan().setVisible(true);
        this.dispose();
    }
    else if (idkegiatan.equals("Survey"))
    {
        new Form_Survey().setVisible(true);
        this.dispose();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        nomor = new javax.swing.JLabel();
        mitra = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        dana = new javax.swing.JLabel();
        cp = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        telp = new javax.swing.JLabel();
        kategori = new javax.swing.JLabel();
        tnomor = new javax.swing.JTextField();
        tmitra = new javax.swing.JTextField();
        tdana = new javax.swing.JTextField();
        tnama = new javax.swing.JTextField();
        temail = new javax.swing.JTextField();
        ttelp = new javax.swing.JTextField();
        tipekegiatan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        SavenExit = new javax.swing.JButton();
        Saveornext = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(0, 0, 102));
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("Input Data Kegiatan");
        jPanel1.add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 324, 74));

        nomor.setText("Nomor Kegiatan");
        jPanel1.add(nomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 114, -1, 20));

        mitra.setText("Mitra Institusi");
        jPanel1.add(mitra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        tgl.setText("Ajukan Tanggal Kegiatan");
        jPanel1.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 186, -1));

        dana.setText("Sumber Dana");
        jPanel1.add(dana, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        cp.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        cp.setText("Contact Person");
        jPanel1.add(cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        nama.setText("Nama Lengkap");
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, 20));

        email.setText("Alamat E-mail");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, 20));

        telp.setText("No Telp");
        jPanel1.add(telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, 20));

        kategori.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        kategori.setText("Kategori Kegiatan");
        jPanel1.add(kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        tnomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnomorActionPerformed(evt);
            }
        });
        jPanel1.add(tnomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 350, -1));
        jPanel1.add(tmitra, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 350, -1));
        jPanel1.add(tdana, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 350, -1));
        jPanel1.add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 350, -1));
        jPanel1.add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 350, -1));
        jPanel1.add(ttelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 350, -1));

        tipekegiatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Silahkan pilih --", "Konsultasi", "Pelatihan", "Survey" }));
        jPanel1.add(tipekegiatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 170, -1));

        jLabel1.setText("Tipe Kegiatan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        SavenExit.setText("Save or Exit");
        SavenExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavenExitActionPerformed(evt);
            }
        });
        jPanel1.add(SavenExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, -1, 38));

        Saveornext.setText("Save or Next");
        Saveornext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveornextActionPerformed(evt);
            }
        });
        jPanel1.add(Saveornext, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, -1, 38));

        jButton3.setText("Cancel");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 84, 39));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 350, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tnomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnomorActionPerformed

    private void SaveornextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveornextActionPerformed
        // TODO add your handling code here:
        //save()
        getform();
                      
    }//GEN-LAST:event_SaveornextActionPerformed

    private void SavenExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavenExitActionPerformed
        // TODO add your handling code here:
        //save()
        new Menubar().setVisible(true);
        this.dispose();
        this.dispose();
    }//GEN-LAST:event_SavenExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKegiatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKegiatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SavenExit;
    private javax.swing.JButton Saveornext;
    private javax.swing.JLabel cp;
    private javax.swing.JLabel dana;
    private javax.swing.JLabel email;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel kategori;
    private javax.swing.JLabel mitra;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nomor;
    private javax.swing.JTextField tdana;
    private javax.swing.JLabel telp;
    private javax.swing.JTextField temail;
    private javax.swing.JLabel tgl;
    private javax.swing.JComboBox<String> tipekegiatan;
    private javax.swing.JTextField tmitra;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnomor;
    private javax.swing.JTextField ttelp;
    // End of variables declaration//GEN-END:variables
}
