/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendaftaran;

/**
 *
 * @author Swift 3
 */
public class Form_Pelatihan extends javax.swing.JFrame {

    /**
     * Creates new form Form_Pelatihan
     */
    public Form_Pelatihan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        jenis = new javax.swing.JLabel();
        tambahan = new javax.swing.JLabel();
        tambahan2 = new javax.swing.JLabel();
        tempat = new javax.swing.JLabel();
        metode = new javax.swing.JLabel();
        combojenis = new javax.swing.JComboBox<>();
        ttambahan = new javax.swing.JTextField();
        ttempat = new javax.swing.JTextField();
        combometode = new javax.swing.JComboBox<>();
        bnext = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        bcancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        metode1 = new javax.swing.JLabel();
        ttempat1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("FORM PELATIHAN");
        getContentPane().add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 227, 49));

        jenis.setText("Jenis Pelatihan / Kegiatan kami");
        getContentPane().add(jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 20));

        tambahan.setText("Tambahkan Nama Pelatihan");
        tambahan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(tambahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 211, -1, 20));

        tambahan2.setText("yang diajukan Bapak / Ibu");
        tambahan2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(tambahan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, 20));

        tempat.setText("Tempat Pelatihan / Kegiatan");
        getContentPane().add(tempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        metode.setText("Nama Peneliti");
        getContentPane().add(metode, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        combojenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pelatihan Analisis Kebijakan Kesehatan", "Pelatihan Rencana Strategi Bisnis Rumah Sakit", "Pelatihan Kepemimpinan Bagi Kepala Unit/Instalasi Rumah Sakit", "Pelatihan Keselamatan Pasien & Manajemen Resiko di Rumah Sakit", "Pelatihan Clinical Pathway", "Pelatihan Monitoring & Evaluasi Program Kesehatan", "Pelatihan Manajemen Lean", "Pelatihan Regulatory Impact Assessment", "Pelatihan Pemanfaatan Data Rumah Sakit", "Pelatihan Peningkatan Kapasistas & Kapabilitas Perencanaan Kesehatan Berbasis Hasil Pemantauan dan Evaluasi Program Bagi Manajemen Program", "Pelatihan Capacity Building", "Pelatihan Sistem Informasi Rumah Sakit", "Pelatihan Koder Rumah Sakit", "Pelatihan Unit Cost Layanan RS", "Pelatihan Akreditasi Rumah Sakit", "Pelatihan Mutu Rumah Sakit", "Pelatihan Service Excellent", "Pelatihan Strategic & LO", "Lainnya .." }));
        getContentPane().add(combojenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 482, -1));
        getContentPane().add(ttambahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 482, 42));
        getContentPane().add(ttempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 482, -1));

        combometode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Online", "Offline", "Hybrid", "Onsite" }));
        combometode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combometodeActionPerformed(evt);
            }
        });
        getContentPane().add(combometode, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 225, -1));

        bnext.setText("NEXT");
        bnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnextActionPerformed(evt);
            }
        });
        getContentPane().add(bnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 100, 20));

        bedit.setText("EDIT");
        getContentPane().add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 100, -1));

        bdelete.setText("DELETE");
        getContentPane().add(bdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 100, -1));

        bcancel.setText("CANCEL");
        bcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelActionPerformed(evt);
            }
        });
        getContentPane().add(bcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 100, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 750, 90));

        metode1.setText("Metode Pelatihan yang diajukan");
        getContentPane().add(metode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));
        getContentPane().add(ttempat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 482, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelActionPerformed
        // TODO add your handling code here:
        Menubar tugas = new Menubar();
         tugas.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_bcancelActionPerformed

    private void bnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnextActionPerformed
        // TODO add your handling code here:
        Form_Proses tugas = new Form_Proses();
         tugas.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_bnextActionPerformed

    private void combometodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combometodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combometodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Pelatihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Pelatihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Pelatihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Pelatihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Pelatihan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcancel;
    private javax.swing.JButton bdelete;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bnext;
    private javax.swing.JComboBox<String> combojenis;
    private javax.swing.JComboBox<String> combometode;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jenis;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel metode;
    private javax.swing.JLabel metode1;
    private javax.swing.JLabel tambahan;
    private javax.swing.JLabel tambahan2;
    private javax.swing.JLabel tempat;
    private javax.swing.JTextField ttambahan;
    private javax.swing.JTextField ttempat;
    private javax.swing.JTextField ttempat1;
    // End of variables declaration//GEN-END:variables
}
