/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendaftaran;

/**
 *
 * @author Swift 3
 */
public class Form_Survey extends javax.swing.JFrame {

    /**
     * Creates new form Form_Pelatihan
     */
    public Form_Survey() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        jenis = new javax.swing.JLabel();
        tambahan = new javax.swing.JLabel();
        tambahan2 = new javax.swing.JLabel();
        tempat = new javax.swing.JLabel();
        metode = new javax.swing.JLabel();
        combojenis = new javax.swing.JComboBox<>();
        ttambahan = new javax.swing.JTextField();
        ttempat = new javax.swing.JTextField();
        combometode = new javax.swing.JComboBox<>();
        bnext = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        bcancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ttempat1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul.setFont(new java.awt.Font("Cambria", 1, 26)); // NOI18N
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("FORM SURVEY");
        getContentPane().add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 227, 49));

        jenis.setText("Jenis Survey / Kegiatan kami");
        getContentPane().add(jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        tambahan.setText("Tambahkan Nama Survey");
        tambahan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(tambahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 31));

        tambahan2.setText("yang diajukan Bapak / Ibu");
        tambahan2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(tambahan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 28));

        tempat.setText("Tempat Survey / Kegiatan");
        getContentPane().add(tempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        metode.setText("Metode Survey yang diajukan");
        getContentPane().add(metode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        combojenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Survey Kepuasan Masyarakat pada Puskesmas", "Survey Kepuasan Pelanggan dan Karyawan Rumah Sakit", "Survey Kepuasan Masyarakat pada Suku Dinas", "Survey Kepuasan Pelanggan Internal dan Eksternal", "Survey Budaya Organisasi Rumah Sakit", "Survey Budaya Keselamatan Pasien pada Rumah Sakit", "Lainnya .." }));
        getContentPane().add(combojenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 482, -1));
        getContentPane().add(ttambahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 482, 42));
        getContentPane().add(ttempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 482, -1));

        combometode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Online", "Offline", "Hybrid", "Onsite" }));
        getContentPane().add(combometode, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 225, -1));

        bnext.setText("SAVE");
        bnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnextActionPerformed(evt);
            }
        });
        getContentPane().add(bnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 100, -1));

        bedit.setText("EDIT");
        getContentPane().add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 100, -1));

        bdelete.setText("DELETE");
        getContentPane().add(bdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 100, -1));

        bcancel.setText("CANCEL");
        bcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelActionPerformed(evt);
            }
        });
        getContentPane().add(bcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 100, -1));

        jLabel1.setText("Nama Peneliti");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));
        getContentPane().add(ttempat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 482, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 770, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelActionPerformed
        // TODO add your handling code here:
        Menubar tugas = new Menubar();
         tugas.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_bcancelActionPerformed

    private void bnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnextActionPerformed
        // TODO add your handling code here:
        Form_Proses tugas = new Form_Proses();
         tugas.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_bnextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Survey().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcancel;
    private javax.swing.JButton bdelete;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bnext;
    private javax.swing.JComboBox<String> combojenis;
    private javax.swing.JComboBox<String> combometode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jenis;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel metode;
    private javax.swing.JLabel tambahan;
    private javax.swing.JLabel tambahan2;
    private javax.swing.JLabel tempat;
    private javax.swing.JTextField ttambahan;
    private javax.swing.JTextField ttempat;
    private javax.swing.JTextField ttempat1;
    // End of variables declaration//GEN-END:variables
}
