/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendaftaran;

/**
 *
 * @author Swift 3
 */
public class Form_Proses extends javax.swing.JFrame {

    /**
     * Creates new form Form_Proses
     */
    public Form_Proses() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        namafix = new javax.swing.JLabel();
        update = new javax.swing.JLabel();
        tglmulai = new javax.swing.JLabel();
        tglakhir = new javax.swing.JLabel();
        tnamafix = new javax.swing.JTextField();
        comboupdate = new javax.swing.JComboBox<>();
        ttglmulai = new javax.swing.JTextField();
        ttglakhir = new javax.swing.JTextField();
        bsave = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        bcancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul.setFont(new java.awt.Font("Cambria", 1, 26)); // NOI18N
        judul.setText("PROSES KEGIATAN");
        jPanel1.add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 63, -1, -1));

        namafix.setText("Nama Kegiatan");
        jPanel1.add(namafix, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        update.setText("Update Kegiatan");
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        tglmulai.setText("Tanggal Mulai Kegiatan");
        jPanel1.add(tglmulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        tglakhir.setText("Sampai Tanggal Akhir Kegiatan");
        jPanel1.add(tglakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        tnamafix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamafixActionPerformed(evt);
            }
        });
        jPanel1.add(tnamafix, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 580, -1));

        comboupdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Dimulai", "On Progress", "Pembuatan Laporan", "Done" }));
        jPanel1.add(comboupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 200, -1));
        jPanel1.add(ttglmulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 150, -1));
        jPanel1.add(ttglakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 150, -1));

        bsave.setText("SAVE");
        jPanel1.add(bsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 100, -1));

        bedit.setText("EDIT");
        jPanel1.add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 100, -1));

        bdelete.setText("DELETE");
        jPanel1.add(bdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 100, -1));

        bcancel.setText("CANCEL");
        bcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelActionPerformed(evt);
            }
        });
        jPanel1.add(bcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tnamafixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamafixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamafixActionPerformed

    private void bcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelActionPerformed
        // TODO add your handling code here:
        Menubar tugas = new Menubar();
         tugas.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_bcancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Proses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Proses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Proses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Proses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Proses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcancel;
    private javax.swing.JButton bdelete;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bsave;
    private javax.swing.JComboBox<String> comboupdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel namafix;
    private javax.swing.JLabel tglakhir;
    private javax.swing.JLabel tglmulai;
    private javax.swing.JTextField tnamafix;
    private javax.swing.JTextField ttglakhir;
    private javax.swing.JTextField ttglmulai;
    private javax.swing.JLabel update;
    // End of variables declaration//GEN-END:variables
}
