/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendaftaran;

import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent; 
import pendaftaran.Koneksi;

/**
 *
 * @author Swift 3
 */
public class Menubar extends javax.swing.JFrame {

    /**
     * Creates new form Menubar
     */
    public Menubar() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (dim.width-getWidth())/2;
        int y = (dim.height-getHeight())/2;
        setLocation(x,y);        
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        profile = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        master = new javax.swing.JMenu();
        peneliti = new javax.swing.JMenuItem();
        pegawai = new javax.swing.JMenuItem();
        Dpetugas = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        inputkegiatan = new javax.swing.JMenuItem();
        MKonsultasi = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Sistem Informasi");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("PENDAFTARAN PELATIHAN, SURVEY, DAN KONSULTASI");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo CHAMPS.png"))); // NOI18N

        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        profile.setText("Profile");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        home.add(profile);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        home.add(exit);

        jMenuBar1.add(home);

        master.setText("Master");
        master.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masterMouseClicked(evt);
            }
        });
        master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterActionPerformed(evt);
            }
        });

        peneliti.setText("Data Peneliti");
        peneliti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penelitiMouseClicked(evt);
            }
        });
        peneliti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penelitiActionPerformed(evt);
            }
        });
        master.add(peneliti);

        pegawai.setText("Data Pegawai");
        pegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pegawaiActionPerformed(evt);
            }
        });
        master.add(pegawai);

        Dpetugas.setText("Data Petugas");
        Dpetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DpetugasMouseClicked(evt);
            }
        });
        Dpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DpetugasActionPerformed(evt);
            }
        });
        master.add(Dpetugas);

        jMenuBar1.add(master);

        transaksi.setText("Transaksi");
        transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiMouseClicked(evt);
            }
        });
        transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiActionPerformed(evt);
            }
        });

        inputkegiatan.setText("Input Kegiatan");
        inputkegiatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputkegiatanActionPerformed(evt);
            }
        });
        transaksi.add(inputkegiatan);

        MKonsultasi.setText("Input Konsultasi");
        MKonsultasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MKonsultasiActionPerformed(evt);
            }
        });
        transaksi.add(MKonsultasi);

        jMenuItem1.setText("Input Pelatihan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        transaksi.add(jMenuItem1);

        jMenuItem2.setText("Input Survey");
        transaksi.add(jMenuItem2);

        jMenuBar1.add(transaksi);

        jMenu1.setText("Report");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(60, 60, 60)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseClicked
       
    }//GEN-LAST:event_transaksiMouseClicked

    private void masterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_masterMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        
    }//GEN-LAST:event_homeMouseClicked

    private void transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transaksiActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
       
    }//GEN-LAST:event_homeActionPerformed

    private void penelitiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penelitiActionPerformed
        // TODO add your handling code here:
        formdatapeneliti tugas = new formdatapeneliti();
         tugas.setVisible(true);
         this.setVisible(false);
         this.setVisible(false);
    }//GEN-LAST:event_penelitiActionPerformed

    private void pegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegawaiActionPerformed
        // TODO add your handling code here:
        formdatapegawai tugas = new formdatapegawai();
         tugas.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_pegawaiActionPerformed

    private void masterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masterActionPerformed

    private void penelitiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penelitiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_penelitiMouseClicked

    private void DpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DpetugasActionPerformed
        // TODO add your handling code here:
        new formdatapetugas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DpetugasActionPerformed

    private void DpetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DpetugasMouseClicked
        // TODO add your handling code here:
        new formdatapetugas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DpetugasMouseClicked

    private void inputkegiatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputkegiatanActionPerformed
        // TODO add your handling code here:
       new FormKegiatan().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_inputkegiatanActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
       new login().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_profileActionPerformed

    private void MKonsultasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MKonsultasiActionPerformed
        // TODO add your handling code here:
        new Form_Konsultan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MKonsultasiActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menubar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menubar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menubar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menubar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menubar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Dpetugas;
    private javax.swing.JMenuItem MKonsultasi;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu home;
    private javax.swing.JMenuItem inputkegiatan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu master;
    private javax.swing.JMenuItem pegawai;
    private javax.swing.JMenuItem peneliti;
    private javax.swing.JMenuItem profile;
    private javax.swing.JMenu transaksi;
    // End of variables declaration//GEN-END:variables
}
